import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import type { ReactNode } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}

// WHY THIS IS A PASSTHROUGH — do not add <html> or <body> here:
// next-intl requires app/[locale]/layout.tsx to render <html lang dir>
// so each route gets the correct lang= and dir= attributes per locale
// (critical for RTL Arabic rendering and screen-reader locale detection).
//
// Having BOTH this file AND [locale]/layout.tsx render <html><body>
// produces nested <html> tags — invalid HTML and a Next.js hydration crash.
//
// Next.js App Router requires this file to exist at the root, but it does NOT
// require it to render the HTML shell. The locale layout owns that entirely.
//
// WHY not `children as unknown as JSX.Element`:
// In strict TypeScript (React 19 + Next.js 16), the global JSX namespace is not
// automatically available unless you import React. Casting to JSX.Element throws
// TS2503. Using a React fragment <>{children}</> returns JSX.Element implicitly
// from the JSX transform — no cast, no error.
